# Generated by Django 4.1.13 on 2026-01-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Vector de 384 dimensions per cerca semàntica', null=True, verbose_name='Vector semàntic'),
        ),
        migrations.AddField(
            model_name='event',
            name='embedding_model',
            field=models.CharField(blank=True, help_text='Nom del model de sentence-transformers utilitzat', max_length=200, null=True, verbose_name="Model d'embedding utilitzat"),
        ),
        migrations.AddField(
            model_name='event',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, help_text="Última vegada que es va calcular l'embedding", null=True, verbose_name='Data actualització embedding'),
        ),
    ]
